### PR TITLE
Reusability by composition instead of inheritance.

### PR DESCRIPTION
**Pull request by marcelo-schroeder**
The main objective of this fork has been to change from a "reuse by inheritance" model to a "reuse by composition" model. This change allows the functionality provided by this component to be more easily integrated into existing projects where, for instance, the target view controller already inherits from another custom view controller (which was my case).

The bulk of the changes revolved around moving functionality from DBMapSelectorViewController to a new class called DBMapSelectorManager which simply subclasses NSObject (i.e. it's simply a helper class).

For a cleaner design, I have removed code related to showing pins on the map as I think this should be responsibility of the client view controller and not the new helper class.

### CODE REVIEW

**Comment by d0ping** [comment]
Yep, you right. How I myself didn't think of this before? 
I think your approach is more correct. Using Manager instead ViewController make component more flexible.
Thank you for your solution.

**Comment by marcelo-schroeder** [comment]
No worries. Thanks to you for the initial version! :-)

**Comment by d0ping** [comment]
Added your solution on the last version (1.2.0). Thanks again!

**Comment by marcelo-schroeder** [comment]
Excellent! I have just integrated your new version and all seems to work. Thanks.

**Pull request merged**
